/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinProfileRouteImport } from './routes/skin-profile'
import { Route as QuizResultRouteImport } from './routes/quiz-result'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductDetailRouteImport } from './routes/product-detail'
import { Route as ProductsIdV2RouteImport } from './routes/products.$id-v2'

const SkinProfileRoute = SkinProfileRouteImport.update({
  id: '/skin-profile',
  path: '/skin-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizResultRoute = QuizResultRouteImport.update({
  id: '/quiz-result',
  path: '/quiz-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDetailRoute = ProductDetailRouteImport.update({
  id: '/product-detail',
  path: '/product-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdV2Route = ProductsIdV2RouteImport.update({
  id: '/$id-v2',
  path: '/$id-v2',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/product-detail': typeof ProductDetailRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz-result': typeof QuizResultRoute
  '/skin-profile': typeof SkinProfileRoute
  '/products/$id-v2': typeof ProductsIdV2Route
}
export interface FileRoutesByTo {
  '/product-detail': typeof ProductDetailRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz-result': typeof QuizResultRoute
  '/skin-profile': typeof SkinProfileRoute
  '/products/$id-v2': typeof ProductsIdV2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/product-detail': typeof ProductDetailRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz-result': typeof QuizResultRoute
  '/skin-profile': typeof SkinProfileRoute
  '/products/$id-v2': typeof ProductsIdV2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/product-detail'
    | '/products'
    | '/quiz-result'
    | '/skin-profile'
    | '/products/$id-v2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/product-detail'
    | '/products'
    | '/quiz-result'
    | '/skin-profile'
    | '/products/$id-v2'
  id:
    | '__root__'
    | '/product-detail'
    | '/products'
    | '/quiz-result'
    | '/skin-profile'
    | '/products/$id-v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProductDetailRoute: typeof ProductDetailRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuizResultRoute: typeof QuizResultRoute
  SkinProfileRoute: typeof SkinProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skin-profile': {
      id: '/skin-profile'
      path: '/skin-profile'
      fullPath: '/skin-profile'
      preLoaderRoute: typeof SkinProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-result': {
      id: '/quiz-result'
      path: '/quiz-result'
      fullPath: '/quiz-result'
      preLoaderRoute: typeof QuizResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-detail': {
      id: '/product-detail'
      path: '/product-detail'
      fullPath: '/product-detail'
      preLoaderRoute: typeof ProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id-v2': {
      id: '/products/$id-v2'
      path: '/$id-v2'
      fullPath: '/products/$id-v2'
      preLoaderRoute: typeof ProductsIdV2RouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsIdV2Route: typeof ProductsIdV2Route
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdV2Route: ProductsIdV2Route,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProductDetailRoute: ProductDetailRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuizResultRoute: QuizResultRoute,
  SkinProfileRoute: SkinProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
