/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentTalk2RouteImport } from './routes/treatment-talk2'
import { Route as TreatmentTalkRouteImport } from './routes/treatment-talk'
import { Route as TeaProductsRouteImport } from './routes/tea-products'
import { Route as SurgeryTalkRouteImport } from './routes/surgery-talk'
import { Route as SkinProfileRouteImport } from './routes/skin-profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizResultRouteImport } from './routes/quiz-result'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductDetailRouteImport } from './routes/product-detail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsIdV2RouteImport } from './routes/products.$id-v2'
import { Route as AdminTreatmentsRouteImport } from './routes/admin.treatments'

const TreatmentTalk2Route = TreatmentTalk2RouteImport.update({
  id: '/treatment-talk2',
  path: '/treatment-talk2',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentTalkRoute = TreatmentTalkRouteImport.update({
  id: '/treatment-talk',
  path: '/treatment-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const TeaProductsRoute = TeaProductsRouteImport.update({
  id: '/tea-products',
  path: '/tea-products',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeryTalkRoute = SurgeryTalkRouteImport.update({
  id: '/surgery-talk',
  path: '/surgery-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinProfileRoute = SkinProfileRouteImport.update({
  id: '/skin-profile',
  path: '/skin-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizResultRoute = QuizResultRouteImport.update({
  id: '/quiz-result',
  path: '/quiz-result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDetailRoute = ProductDetailRouteImport.update({
  id: '/product-detail',
  path: '/product-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdV2Route = ProductsIdV2RouteImport.update({
  id: '/$id-v2',
  path: '/$id-v2',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminTreatmentsRoute = AdminTreatmentsRouteImport.update({
  id: '/admin/treatments',
  path: '/admin/treatments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinics': typeof ClinicsRoute
  '/login': typeof LoginRoute
  '/product-detail': typeof ProductDetailRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/quiz-result': typeof QuizResultRoute
  '/signup': typeof SignupRoute
  '/skin-profile': typeof SkinProfileRoute
  '/surgery-talk': typeof SurgeryTalkRoute
  '/tea-products': typeof TeaProductsRoute
  '/treatment-talk': typeof TreatmentTalkRoute
  '/treatment-talk2': typeof TreatmentTalk2Route
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/products/$id-v2': typeof ProductsIdV2Route
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinics': typeof ClinicsRoute
  '/login': typeof LoginRoute
  '/product-detail': typeof ProductDetailRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/quiz-result': typeof QuizResultRoute
  '/signup': typeof SignupRoute
  '/skin-profile': typeof SkinProfileRoute
  '/surgery-talk': typeof SurgeryTalkRoute
  '/tea-products': typeof TeaProductsRoute
  '/treatment-talk': typeof TreatmentTalkRoute
  '/treatment-talk2': typeof TreatmentTalk2Route
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/products/$id-v2': typeof ProductsIdV2Route
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinics': typeof ClinicsRoute
  '/login': typeof LoginRoute
  '/product-detail': typeof ProductDetailRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/quiz-result': typeof QuizResultRoute
  '/signup': typeof SignupRoute
  '/skin-profile': typeof SkinProfileRoute
  '/surgery-talk': typeof SurgeryTalkRoute
  '/tea-products': typeof TeaProductsRoute
  '/treatment-talk': typeof TreatmentTalkRoute
  '/treatment-talk2': typeof TreatmentTalk2Route
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/products/$id-v2': typeof ProductsIdV2Route
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinics'
    | '/login'
    | '/product-detail'
    | '/products'
    | '/quiz'
    | '/quiz-result'
    | '/signup'
    | '/skin-profile'
    | '/surgery-talk'
    | '/tea-products'
    | '/treatment-talk'
    | '/treatment-talk2'
    | '/admin/treatments'
    | '/products/$id-v2'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinics'
    | '/login'
    | '/product-detail'
    | '/products'
    | '/quiz'
    | '/quiz-result'
    | '/signup'
    | '/skin-profile'
    | '/surgery-talk'
    | '/tea-products'
    | '/treatment-talk'
    | '/treatment-talk2'
    | '/admin/treatments'
    | '/products/$id-v2'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/clinics'
    | '/login'
    | '/product-detail'
    | '/products'
    | '/quiz'
    | '/quiz-result'
    | '/signup'
    | '/skin-profile'
    | '/surgery-talk'
    | '/tea-products'
    | '/treatment-talk'
    | '/treatment-talk2'
    | '/admin/treatments'
    | '/products/$id-v2'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicsRoute: typeof ClinicsRoute
  LoginRoute: typeof LoginRoute
  ProductDetailRoute: typeof ProductDetailRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuizRoute: typeof QuizRoute
  QuizResultRoute: typeof QuizResultRoute
  SignupRoute: typeof SignupRoute
  SkinProfileRoute: typeof SkinProfileRoute
  SurgeryTalkRoute: typeof SurgeryTalkRoute
  TeaProductsRoute: typeof TeaProductsRoute
  TreatmentTalkRoute: typeof TreatmentTalkRoute
  TreatmentTalk2Route: typeof TreatmentTalk2Route
  AdminTreatmentsRoute: typeof AdminTreatmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatment-talk2': {
      id: '/treatment-talk2'
      path: '/treatment-talk2'
      fullPath: '/treatment-talk2'
      preLoaderRoute: typeof TreatmentTalk2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment-talk': {
      id: '/treatment-talk'
      path: '/treatment-talk'
      fullPath: '/treatment-talk'
      preLoaderRoute: typeof TreatmentTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tea-products': {
      id: '/tea-products'
      path: '/tea-products'
      fullPath: '/tea-products'
      preLoaderRoute: typeof TeaProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgery-talk': {
      id: '/surgery-talk'
      path: '/surgery-talk'
      fullPath: '/surgery-talk'
      preLoaderRoute: typeof SurgeryTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-profile': {
      id: '/skin-profile'
      path: '/skin-profile'
      fullPath: '/skin-profile'
      preLoaderRoute: typeof SkinProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-result': {
      id: '/quiz-result'
      path: '/quiz-result'
      fullPath: '/quiz-result'
      preLoaderRoute: typeof QuizResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-detail': {
      id: '/product-detail'
      path: '/product-detail'
      fullPath: '/product-detail'
      preLoaderRoute: typeof ProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id-v2': {
      id: '/products/$id-v2'
      path: '/$id-v2'
      fullPath: '/products/$id-v2'
      preLoaderRoute: typeof ProductsIdV2RouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/treatments': {
      id: '/admin/treatments'
      path: '/admin/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AdminTreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsIdV2Route: typeof ProductsIdV2Route
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdV2Route: ProductsIdV2Route,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicsRoute: ClinicsRoute,
  LoginRoute: LoginRoute,
  ProductDetailRoute: ProductDetailRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuizRoute: QuizRoute,
  QuizResultRoute: QuizResultRoute,
  SignupRoute: SignupRoute,
  SkinProfileRoute: SkinProfileRoute,
  SurgeryTalkRoute: SurgeryTalkRoute,
  TeaProductsRoute: TeaProductsRoute,
  TreatmentTalkRoute: TreatmentTalkRoute,
  TreatmentTalk2Route: TreatmentTalk2Route,
  AdminTreatmentsRoute: AdminTreatmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
